global:
  user: "${env:USER:-admin}"

devices:
- type: "SHPLG-S"
  ip: "10.1.3.117"
  password: "${env:SHELLY_PASSWORD}"
- type: "SHPLG-S"
  ip: "10.1.3.100"
  password: "${env:SHELLY_PASSWORD}"
- type: "SHPLG-S"
  ip: "10.1.3.154"
  password: "${env:SHELLY_PASSWORD}"
