name: Run Tests

on:
  pull_request:
  push:
    branches:
      - "*"
    tags:
      - "!v*"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Gofumpt
        run: |-
          go get mvdan.cc/gofumpt
          if [ "$(gofumpt -l . | wc -l)" -gt 0 ]; then gofumpt -d . && exit 1; fi

      - name: Go mod download
        run: go mod download

      - name: Go Vet
        run: go vet ./...

      - name: Go Build
        run: go build ./cmd/...

      - name: Go Test
        run: go test ./...
